# Generated by Django 5.0.3 on 2024-03-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='doctor',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
